name: "Modbus 2 MQTT"
description: "Modbus 2 MQTT"
version: "1.0.0-alpha-2"
slug: "modbus2mqtt"
init: false
hassio_api: true
homeassistant_api: true
hassio_role: admin
# map:
#   - addons:rw
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
