name: "Modbus 2 MQTT"
description: "Modbus 2 MQTT"
version: "1.0.5"
slug: "example"
init: false
hassio_api: true
homeassistant_api: true
hassio_role: admin
map:
  - addons:rw
arch:
  - armv7
  - i386
