name: "Modbus 2 MQTT"
description: "Modbus 2 MQTT"
version: "1.0.0"
slug: "modbus2mqtt"
init: false
host_network: true
# ingress: true
homeassistant_api: true
map:
  - addons:rw
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
options:
schema:
